spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:work
    username: work
    password: Start123!
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  flyway:
    user: work
    password: Start123!
    url: jdbc:h2:mem:work
    locations: classpath:sql
url:
  nbp: http://api.nbp.pl/api/exchangerates/tables/
cron:
  currency: 0 0 0/6 ? * *