CREATE TABLE IF NOT EXISTS USER (
    ID NUMBER(19) NOT NULL,
    NAME VARCHAR(70) NOT NULL,
    SURNAME VARCHAR(100) NOT NULL,
    PESEL VARCHAR(11) NOT NULL,
    CONSTRAINT USER_ID PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS ACCOUNT (
    ID NUMBER(19) NOT NULL,
    IBAN VARCHAR(28) NOT NULL,
    CURRENCY VARCHAR(3) NOT NULL,
    MONEY NUMBER(12,2) NOT NULL,
    USER_ID NUMBER(19) NOT NULL,
    CONSTRAINT ACCOUNT_ID PRIMARY KEY(ID),
    CONSTRAINT ACCOUNT_USER_KEY FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE IF NOT EXISTS SUB_ACCOUNT (
    ID NUMBER(19) NOT NULL,
    CURRENCY VARCHAR(3) NOT NULL,
    ACCOUNT_ID NUMBER(19) NOT NULL,
    CONSTRAINT SUB_ACCOUNT_ID PRIMARY KEY(ID),
    CONSTRAINT SUB_ACCOUNT_ACCOUNT_KEY FOREIGN KEY (ACCOUNT_ID) REFERENCES USER(ID)
);